// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "goagen_js": Application User Types
//
// Command:
// $ goagen
// --design=github.com/shirou/goagen_js/example/design
// --out=$(GOPATH)src/github.com/shirou/goagen_js/example
// --version=v1.2.0-dirty

package app

// getParamPayload user type.
type getParamPayload struct {
	ParamStr *string `form:"ParamStr,omitempty" json:"ParamStr,omitempty" xml:"ParamStr,omitempty"`
}

// Publicize creates GetParamPayload from getParamPayload
func (ut *getParamPayload) Publicize() *GetParamPayload {
	var pub GetParamPayload
	if ut.ParamStr != nil {
		pub.ParamStr = ut.ParamStr
	}
	return &pub
}

// GetParamPayload user type.
type GetParamPayload struct {
	ParamStr *string `form:"ParamStr,omitempty" json:"ParamStr,omitempty" xml:"ParamStr,omitempty"`
}
